### ISSUE TITLE
XML comparison sometimes gives erroneous errors with attributes in different order

### ISSUE THREAD

**Issue by murrayju** [prettydiff/prettydiff#104]
Prettydiff usually does a good job of ignoring differences just in the order of attributes. However, I've found some cases where it doesn't work. In the output, the attributes do not appear to be sorted on the offending lines.

Here is an example gist containing two files to diff:
https://gist.github.com/murrayju/5d99c370e06176044fa0
(I'm confident that they are equal, oXygen's diff tool agrees)

**Comment by prettydiff** [comment]
I was able to reproduce differences in Chrome but not Firefox. Since the behavior is not consistent between browsers and since both the input and the Pretty Diff application code are consistent between browsers I am extremely confident at placing the blame on [Array.prototype.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

**Extremely long and boring explanation follows**

This is complete failure of the JavaScript language. The [specification](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.11) is the primary culprit, but implementers have to share in some of that stupidity. The failure is that the spec provides an algorithm based upon data symmetry without providing the implementation of the algorithm. It goes further to state that behavior (stability) is implementation dependent and so conformance is irrelevant. The entire point of a standards specification is to achieve some degree of conformance.... therefore failure.

What's interesting is not so much that the technology is a failure, but that the failure is allowed to exist because certain parties believe the definition supplied is more important that the technology resultant from that definition.  Here is where I got flamed for challenging dogma: http://www.reddit.com/r/javascript/comments/33jlzo/sort_algorithms_and_chromes_shameful_secret/cqljabn

Fortunately, I have solved this problem with technology: [safeSort](https://github.com/prettydiff/safeSort). This solution is vastly superior in that it is always stable, always predictable, and implementation independent. Also it automagically sorts by type and value, which the native sort method does not. The two limitations to this superior form of sort:

* twice as slow since it gets no bonus from native code in the JIT
* it cannot configured to accept child array indexes as keys to sort by in case of advanced sorting of multidimensional arrays

I am integrate safeSort into Pretty Diff to solve this problem forever (since I have encountered it before).

**Comment by murrayju** [comment]
@prettydiff thank's for the detailed explanation. I totally agree with your assessment.

Just to be clear, you saying that this issue is the result of some dependence on a stable sort (and the browser implementation is not stable), not that it failed to sort altogether. Right?

I've also run into this problem before, and was happy to solve it using the [underscore](http://underscorejs.org/#sortBy)/[lodash](https://lodash.com/docs#sortBy) `sortBy` function, which it documents as being stable. I was happy to see when I just checked again that it does *not* fall back on the native sort. How does your safeSort compare to these (performance or otherwise)?

**Comment by prettydiff** [comment]
> Just to be clear, you saying that this issue is the result of some dependence on a stable sort (and the browser implementation is not stable), not that it failed to sort altogether. Right?

Yes, exactly. The browser's native sort method requires use of a function that sets the sort criteria and must return either -1, 0, or 1 as values. The challenge here is that if the logic presented in that function does not maintain considerations of data symmetry in the most confined and unidirectional manner the result is unpredictable.  Unfortunately, data symmetry is not a primary concern of most users who merely want their data organized either alphabetically or by type and either ascending or descending.

**Comment by murrayju** [comment]
In an attempt to work around this, I wrote a simple stable sort around the native sort, and overrode `Array.prototype.sort` with it. Here is the algorithm: https://gist.github.com/murrayju/d399b2b9a542698417fd

However, I'm still seeing the same sort of failure in prettydiff. Any reason why this approach wouldn't work?

**Comment by murrayju** [comment]
@prettydiff I looked into this a bit more, and I'm wondering about the implementation of the compareTo function for attributes.
[markupmin.js line 157](https://github.com/prettydiff/prettydiff/blob/master/lib/markupmin.js#L157):
```js
sortfunc    = function markup_beauty__algorithm_loop_attributeOrder_sortfunc(aaa, bbb) {
  if (aaa > bbb) {
    return 1;
  }
  return 0;
}
```

I don't understand why you don't have a case that returns `-1`, like this:
```js
sortfunc    = function markup_beauty__algorithm_loop_attributeOrder_sortfunc(aaa, bbb) {
  if (aaa > bbb) {
    return 1;
  }
  if (aaa < bbb) {
    return -1;
  }
  return 0;
}
```

Making this change, I seem to get better results. I may be running into other issues now though, still trying to narrow those down.

**Comment by prettydiff** [comment]
A beta version of the new markup parser is up. This version is feature complete, but not fully tested against edge cases.

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

Please test this out and try to break it. If you encounter any issues please post them here.  This is likely to be buggy because it is completely new parser written from scratch in the past two weeks.

**Comment by murrayju** [comment]
@prettydiff Any reason why the code isn't pushed to this github repo? All of my tests are designed to execute the code directly, not use a web endpoint.

**Comment by prettydiff** [comment]
Yeah, I am still doing edge case testing. I want to ensure that at the very least the new parser is at least as stable as the old parser. Validation will get much more automated once I build a test harness for QA automation on the command line. I was going to get to this next.

**Comment by murrayju** [comment]
Can you push it to a feature branch? I have a large number of automated tests that pass using the current code. I could easily run them against the new code if it is pushed. I don't have time to do a lot of manual testing.

**Comment by prettydiff** [comment]
Done. checkout branch `markuppretty-init`

**Comment by murrayju** [comment]
Seems like there may be some regression. For example, here is a gist of two files to diff:
https://gist.github.com/murrayju/084caa5997d255f7a8db

The old code reports 0 differences, the new code reports 198 differences. A simple text diff tool shows that these actually only differ by some unimportant whitespace.

**Comment by prettydiff** [comment]
Thank you so much for reporting that. I just fixed it and pushed the change to the branch.

**Comment by murrayju** [comment]
Just tried again with the latest code, and I'm still seeing failures around whitespace in self-closing tags (`<title />` different than `<title/>`).

**Comment by prettydiff** [comment]
Yep, you are right. I made an additional correction for this.

**Comment by murrayju** [comment]
Much better. All of the tests that pass with the old code now pass with the new code as well.

I tried running the tests that I originally created this issue for, but those are still failing. I'll investigate more on Monday to see if they are still failing for the same reasons.

**Comment by prettydiff** [comment]
Fixed as v1.12.0
